"""news table

Revision ID: ee9463d53f15
Revises: 333f01e580eb
Create Date: 2022-10-10 08:47:08.555258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9463d53f15'
down_revision = '333f01e580eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('link', sa.String(length=2046), nullable=True),
    sa.Column('clean_url', sa.String(length=128), nullable=True),
    sa.Column('excerpt', sa.String(length=1024), nullable=True),
    sa.Column('media', sa.String(length=2046), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
